<a href="https://colab.research.google.com/github/HaveFaith07/HaveFaith-Project/blob/Machine-Learning/EnsembleLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import pandas as pd
import sklearn.metrics
import sklearn.ensemble
import sklearn.model_selection

In [18]:
df=pd.read_csv("mnist.csv")
df.set_index('id')
df.head()

,id,class,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,31953,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,34452,8,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,60897,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,36953,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1981,3,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
x=df.drop(["class"],axis=1)
y=df["class"]
x_train,x_test,y_train,y_test = sklearn.model_selection.train_test_split(x,y)

In [22]:
parameters_grid={
    "criterion":["gini","entropy"],
    "n_estimators":range(50,240,50)
}
model1= sklearn.model_selection.GridSearchCV(sklearn.ensemble.RandomForestClassifier(),
                                             parameters_grid,scoring="accuracy",cv=5,n_jobs=-1)
model1.fit(x_train,y_train)
print("Accuracy of best Random Forest Classifier = {:.2f}".format(model1.best_score_))
print("Best found hyperparameters of Random Forest classifier = {}".format(model1.best_params_))

Accuracy of best Random Forest Classifier = 0.93
Best found hyperparameters of Random Forest classifier = {'criterion': 'gini', 'n_estimators': 200}

Gradient Boosting

In [ ]:
parameters_grid={
    "learning_rate":[0.01,0.1,0.2],
    "n_estimators":range(50,240,50)

}
model2= sklearn.model_selection.GridSearchCV(sklearn.ensemble.GradientBoostingClassifier(),
                                             parameters_grid,scoring="accuracy",cv=5,n_jobs=-1)
model2.fit(x_train,y_train)
print("Accuracy of best Gradient Boosting Classifier = {:.2f}".format(model2.best_score_))
print("Best found hyperparameters of Gradient Boosting classifier = {}".format(model2.best_params_))

In [ ]:
y_predicted=model1.predict(x_test)
accuracy=sklearn.metrics.accuracy_score(y_test,y_predicted)
cm=sklearn.metrics.confusion_matrix(y_test,y_predicted)
precision,recall,f1,support=sklearn.,metrics.precision_recall_fscore_support(y_test,y_predicted)

print("Accuracy =",accuracy)
print("Precision",precision)
print("Recall",recall)
print("F1-score",f1)
print("Confusion Matrix:\n",cm)